name: project_9shop
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.1 #onBoarding Screen
  get_storage: ^2.1.1   #chức năng hiển thị onboarding lần đầu login
  flutter_iconly: ^1.0.2 #icon bottom navigation bar
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  getwidget: ^4.0.0 #ui kit library
  cached_network_image: ^3.3.0 #lưu ảnh vào bộ nhớ giảm tải load lại
  youtube_player_flutter: ^8.1.2
  # flutterfire_ui: ^0.4.3+20
  firebase_ui_firestore: ^1.5.14
  firebase_ui_database: ^1.3.12
  firebase_auth: ^4.15.0
  uuid: ^3.0.7
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  file_picker: ^6.0.0
  firebase_storage: ^11.3.1
  mime_type: ^1.0.0
  path: ^1.8.3
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  persistent_bottom_nav_bar: ^5.0.2
  expandable_text: ^2.3.0
  flutter_easyloading: ^3.0.5
  toggle_switch: ^2.0.1
  dotted_border: ^2.1.0
  slide_switcher: ^1.1.2
  chips_choice: ^3.0.1
  search_page: ^2.3.0
  flutter_stripe: ^9.5.0+1
  url_launcher: ^6.2.2
  sound_stream_now: ^1.0.0
  # dialogoverflow
  dialog_flowtter: ^0.3.1
  permission_handler: ^11.1.0
  app_settings: ^5.1.1
  speech_to_text: ^6.5.1
  flare_flutter: ^3.0.2
    
  






dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/dialog_flow_auth.json


  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  #         style: italic
    - family: AROneSans
      fonts:
        - asset: assets/fonts/AROneSans-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
